export const DISCOVERY_QUERIES: string[] = [
  // ── Bangla Content ──
  'bangla full movie 2026',
  'new bangla natok 2026',
  'bangla romantic natok full',
  'bangla movie full HD',
  'bangla hit songs official',
  'bangla drama serial full episode',
  'bangladeshi new movie official',
  'eid special natok 2026',
  'bangla folk music video',
  'kolkata bangla movie full',
  'bangla short film 2026',
  'bangla comedy natok new',

  // ── Hindi Content ──
  'hindi full movie 2026',
  'hindi action movie full hd',
  'new hindi songs official music video',
  'hindi drama serial full episode',
  'bollywood movie full HD',
  'hindi romantic songs latest',
  'south indian hindi dubbed full movie',
  'hindi web series episode',
  'latest bollywood video song',
  'hindi thriller full movie',
  'hindi comedy movie full',
  'bollywood classic full movie',

  // ── English Content ──
  'full movie 2026 official',
  'official music video 4k',
  'hollywood action movie full',
  'english pop songs official',
  'full length indie film',
  'official audio music track',
  'sci-fi movie full length',
  'drama movie full HD',
  'latest official music video',
  'classic hollywood movie full',
  'thriller movie full length',
  'official documentary film full',

  // ── Tamil Content ──
  'tamil full movie 2026',
  'tamil new movie full HD',
  'tamil hit songs official video',
  'tamil action movie full',
  'latest tamil music video',
  'tamil romantic movie full',
  'tamil melody songs hd',
  'tamil drama series episode',
  'kollywood full movie hd',
  'tamil comedy movie full',

  // ── Telugu Content ──
  'telugu full movie 2026',
  'telugu new movie full HD',
  'telugu video songs official',
  'telugu action movie full',
  'latest telugu hit songs',
  'tollywood full movie hd',
  'telugu romantic drama full',
  'telugu folk songs official',
  'telugu blockbuster full movie',
  'telugu comedy movie full',

  // ── Urdu Content ──
  'urdu drama serial full episode',
  'pakistani drama 2026 full episode',
  'urdu full movie hd',
  'pakistani official music video',
  'urdu telefilm full',
  'coke studio official music',
  'urdu romantic drama serial',
  'pakistani OST official song',
  'pakistani comedy drama full episode',

  // ── Punjabi Content ──
  'punjabi full movie 2026',
  'punjabi new song official video',
  'pollywood full movie hd',
  'punjabi comedy movie full',
  'latest punjabi hit songs',
  'punjabi romantic movie full',
  'punjabi bhangra music video',
  'punjabi drama movie full',
]
